export const PAGE_WIDTH = 794;
export const PAGE_HEIGHT = 1123;
export const PAGE_GAP = 24;

export const DEFAULT_MARGIN_TOP = 38;
export const DEFAULT_MARGIN_BOTTOM = 38;
export const DEFAULT_MARGIN_LEFT = 113;
export const DEFAULT_MARGIN_RIGHT = 76;
export const DEFAULT_CONTENT_MARGIN_TOP = 57;
export const DEFAULT_CONTENT_MARGIN_BOTTOM = 57;

export const PRINTABLE_HEIGHT =
  PAGE_HEIGHT -
  DEFAULT_MARGIN_TOP -
  DEFAULT_MARGIN_BOTTOM -
  DEFAULT_CONTENT_MARGIN_TOP -
  DEFAULT_CONTENT_MARGIN_BOTTOM;
